# enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 8

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = "'MaterialYou'"
dpi = "nodpi anydpi 120-640dpi"

[Music]
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "arm64-v8a"

[Twitter]
enabled = false
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
cli-source = "inotia00/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitter-inc/twitter/"
arch = "arm64-v8a"
dpi = "nodpi anydpi 120-640dpi"

[Reddit]
# enabled = false
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
# uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# version = "2025.05.0"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
dpi = "nodpi anydpi 120-640dpi"
# arch = "arm64-v8a"

[Messenger]
# enabled = false
# apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
# dpi = "360-480dpi"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
arch = "arm64-v8a"
version = "latest"
excluded-patches = "'Disable switching emoji to sticker'"

[Facebook]
# enabled = false
# apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
arch = "arm64-v8a"
version = "latest"

[Instagram]
# apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl="https://instagram.en.uptodown.com/android"
arch = "arm64-v8a"
excluded-patches = "'Hide navigation buttons'"
dpi = "nodpi anydpi 480dpi"
version = "latest"

[Pixiv]
apkmirror-dlurl = "https://www.apkmirror.com/apk/pixiv-inc/pixiv/"
arch = "arm64-v8a"
